/* 도면 */
CREATE TABLE DRAWING (
	FILE_ID VARCHAR(100) NOT NULL, /* 파일ID */
	FILE_NM VARCHAR(100) NOT NULL, /* 파일명 */
	FILE_CONTENT VARCHAR(1000) NOT NULL, /* 파일내용 */
	FILE_FULL_NM VARCHAR(100) NOT NULL, /* 전체파일명 */
	CRT_ID VARCHAR(100), /* 등록ID */
	CRT_DT DATE, /* 등록시간 */
	CHG_ID VARCHAR(100), /* 수정ID */
	CHG_DT DATE /* 수정시간 */
);

COMMENT ON TABLE DRAWING IS '도면';

COMMENT ON COLUMN DRAWING.FILE_ID IS '파일ID';

COMMENT ON COLUMN DRAWING.FILE_NM IS '파일명';

COMMENT ON COLUMN DRAWING.FILE_CONTENT IS '파일내용';

COMMENT ON COLUMN DRAWING.FILE_FULL_NM IS '전체파일명';

COMMENT ON COLUMN DRAWING.CRT_ID IS '등록ID';

COMMENT ON COLUMN DRAWING.CRT_DT IS '등록시간';

COMMENT ON COLUMN DRAWING.CHG_ID IS '수정ID';

COMMENT ON COLUMN DRAWING.CHG_DT IS '수정시간';



CREATE UNIQUE INDEX PK_DRAWING
	ON DRAWING (
		FILE_ID ASC
	);

ALTER TABLE DRAWING
	ADD
		CONSTRAINT PK_DRAWING
		PRIMARY KEY (
			FILE_ID
		);

/* 아이콘 */
CREATE TABLE ICON (
	ICON_ID VARCHAR(100) NOT NULL, /* 아이콘ID */
	ICON_NM VARCHAR(100) NOT NULL, /* 아이콘명 */
	ICON_CONTENT VARCHAR(1000) NOT NULL, /* 아이콘내용 */
	ICON_FULL_NM VARCHAR(100) NOT NULL, /* 아이콘전체명칭 */
	CRT_ID VARCHAR(100), /* 등록ID */
	CRT_DT DATE, /* 등록시간 */
	CHG_ID VARCHAR(100), /* 수정ID */
	CHG_DT DATE /* 수정시간 */
);

COMMENT ON TABLE ICON IS '아이콘';

COMMENT ON COLUMN ICON.ICON_ID IS '아이콘ID';

COMMENT ON COLUMN ICON.ICON_NM IS '아이콘명';

COMMENT ON COLUMN ICON.ICON_CONTENT IS '아이콘내용';

COMMENT ON COLUMN ICON.ICON_FULL_NM IS '아이콘전체명칭';

COMMENT ON COLUMN ICON.CRT_ID IS '등록ID';

COMMENT ON COLUMN ICON.CRT_DT IS '등록시간';

COMMENT ON COLUMN ICON.CHG_ID IS '수정ID';

COMMENT ON COLUMN ICON.CHG_DT IS '수정시간';

CREATE UNIQUE INDEX PK_ICON
	ON ICON (
		ICON_ID ASC
	);

ALTER TABLE ICON
	ADD
		CONSTRAINT PK_ICON
		PRIMARY KEY (
			ICON_ID
		);

/* 설비 */
CREATE TABLE EQUIPMENT (
	EQP_ID VARCHAR(100) NOT NULL, /* 장비ID */
	FILE_ID VARCHAR(100) NOT NULL, /* 파일ID */
	ICON_ID VARCHAR(100) NOT NULL, /* 아이콘ID */
	EQP_NM VARCHAR(100), /* 장비명 */
	EQP_CONTENT VARCHAR(1000), /* 장비내용 */
	EQP_WIDTH NUMBER, /* 장비Width */
	EQP_HEIGHT NUMBER, /* 장비Height */
	EQP_X NUMBER, /* 장비X */
	EQP_Y NUMBER, /* 장비Y */
	EQP_VISIBLE VARCHAR(1), /* 장비Visible */
	EQP_ENABLE VARCHAR(1), /* 장비Enable */
	CRT_ID VARCHAR(100), /* 등록ID */
	CRT_DT DATE, /* 등록시간 */
	CHG_ID VARCHAR(100), /* 수정ID */
	CHG_DT DATE /* 수정시간 */
);

COMMENT ON TABLE EQUIPMENT IS '설비';

COMMENT ON COLUMN EQUIPMENT.EQP_ID IS '장비ID';

COMMENT ON COLUMN EQUIPMENT.FILE_ID IS '파일ID';

COMMENT ON COLUMN EQUIPMENT.ICON_ID IS '아이콘ID';

COMMENT ON COLUMN EQUIPMENT.EQP_NM IS '장비명';

COMMENT ON COLUMN EQUIPMENT.EQP_CONTENT IS '장비내용';

COMMENT ON COLUMN EQUIPMENT.EQP_WIDTH IS '장비Width';

COMMENT ON COLUMN EQUIPMENT.EQP_HEIGHT IS '장비Height';

COMMENT ON COLUMN EQUIPMENT.EQP_X IS '장비X';

COMMENT ON COLUMN EQUIPMENT.EQP_Y IS '장비Y';

COMMENT ON COLUMN EQUIPMENT.EQP_VISIBLE IS '장비Visible';

COMMENT ON COLUMN EQUIPMENT.EQP_ENABLE IS '장비Enable';

COMMENT ON COLUMN EQUIPMENT.CRT_ID IS '등록ID';

COMMENT ON COLUMN EQUIPMENT.CRT_DT IS '등록시간';

COMMENT ON COLUMN EQUIPMENT.CHG_ID IS '수정ID';

COMMENT ON COLUMN EQUIPMENT.CHG_DT IS '수정시간';

CREATE UNIQUE INDEX PK_EQUIPMENT
	ON EQUIPMENT (
		EQP_ID ASC
	);

ALTER TABLE EQUIPMENT
	ADD
		CONSTRAINT PK_EQUIPMENT
		PRIMARY KEY (
			EQP_ID
		);

ALTER TABLE EQUIPMENT
	ADD
		CONSTRAINT FK_DRAWING_TO_EQUIPMENT
		FOREIGN KEY (
			FILE_ID
		)
		REFERENCES DRAWING (
			FILE_ID
		);

ALTER TABLE EQUIPMENT
	ADD
		CONSTRAINT FK_ICON_TO_EQUIPMENT
		FOREIGN KEY (
			ICON_ID
		)
		REFERENCES ICON (
			ICON_ID
		);